[project]
name = "dukit"
version = "0.2.1"
description = "dukit - data utilities kit for exploring, modifying and visualizing small but messy data using pandas"
readme = "README.md"
authors = [
    { name = "MartinVoelkl94", email = "martinv16248@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipython>=9.15.0",
    "jinja2>=3.1.6",
    "pandas>=3.0.3",
]

[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "faker>=40.28.1",
    "flake8>=7.3.0",
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.8",
    "openpyxl>=3.1.5",
    "pip>=26.1.2",
    "pylance>=8.0.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "viztracer>=1.1.1",
]
