
import pandas as pd
import numpy as np
import datetime


def get_df() -> pd.DataFrame:
    """
    Returns a small sample dataframe containing very messy fake medical data.
    """
    data = {
        'ID': [
            10001,
            10002,
            10003,
            20001,
            20002,
            20003,
            30001,
            30002,
            30003,
            30004,
            30005,
            ],
        'name': [
            'John Doe',
            'Jane Smith',
            'Alice Johnson',
            'Bob Brown',
            'eva white',
            'Frank miller',
            'Grace TAYLOR',
            'Harry Clark',
            'IVY GREEN',
            'JAck Williams',
            'john Doe',
            ],
        'date of birth': [
            pd.to_datetime('1995-01-02'),
            datetime.datetime(1990, 9, 14),
            '1985.08.23',
            '19800406',
            '05-11-2007',
            pd.to_datetime('06-30-1983').date(),
            datetime.datetime(1975, 5, 28).date(),
            '1960Mar08',
            '1955-Jan-09',
            '1950 Sep 10',
            '1945 October 11',
            ],
        'age': [
            -25,
            '30',
            np.nan,
            pd.NaT,
            '40.0',
            'forty-five',
            'nan',
            'unk',
            '',
            'unknown',
            35,
            ],
        'gender': [
            'M',
            'F',
            'Female',
            'Male',
            'Other',
            'm',
            'ff',
            'NaN',
            None,
            'Mal',
            'female',
            ],
        'height': [
            170,
            '175.5cm',
            None,
            '280',
            'NULL',
            '185',
            '1',
            '6ft 1in',
            -10,
            '',
            200,
            ],
        'weight': [
            70.2,
            '68',
            '72.5lb',
            'na',
            '',
            '75kg',
            None,
            '80.3',
            '130lbs',
            '1e2',
            -65,
            ],
        'bp systole': [
            ' 20 ',
            130,
            '<NA>',
            -np.inf,
            '135mmhg',
            '125.5',
            'NAN',
            '122,3',
            '',
            130,
            '45',
            ],
        'bp diastole': [
            80,
            '85',
            'N/A',
            '90mmHg',
            np.nan,
            '75',
            'NaN',
            pd.NA,
            '95',
            '0',
            'None ',
            ],
        'cholesterol': [
            'Normal',
            'Highe',
            'NaN',
            'GOOD',
            'n.a.',
            'High',
            'Normal',
            'n/a',
            'high',
            '',
            'Normal',
            ],
        'diabetes': [
            False,
            'true',
            'N/A',
            0,
            '1',
            'Yes',
            'NO',
            None,
            'NaN',
            'n',
            True,
            ],
        'dose': [
            '10kg',
            'NaN',
            '15 mg once a day',
            '20mg',
            '20 Mg',
            '25g',
            'NaN',
            None,
            '30 MG',
            ' 35 ',
            '40ml',
            ],
        }
    df = pd.DataFrame(data).convert_dtypes()
    df.columns = df.columns.to_series().convert_dtypes()
    df.index = df.index.to_series().convert_dtypes()
    return df
